
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AuthPanel: typeof import("../../app/components/auth/AuthPanel.vue")['default']
  BaseAlert: typeof import("../../app/components/base/BaseAlert.vue")['default']
  BaseBadge: typeof import("../../app/components/base/BaseBadge.vue")['default']
  BaseButton: typeof import("../../app/components/base/BaseButton.vue")['default']
  BaseCard: typeof import("../../app/components/base/BaseCard.vue")['default']
  BaseContainer: typeof import("../../app/components/base/BaseContainer.vue")['default']
  BaseInput: typeof import("../../app/components/base/BaseInput.vue")['default']
  BasePage: typeof import("../../app/components/base/BasePage.vue")['default']
  BaseSection: typeof import("../../app/components/base/BaseSection.vue")['default']
  BaseSelect: typeof import("../../app/components/base/BaseSelect.vue")['default']
  BaseStatCard: typeof import("../../app/components/base/BaseStatCard.vue")['default']
  BaseTable: typeof import("../../app/components/base/BaseTable.vue")['default']
  BaseTextarea: typeof import("../../app/components/base/BaseTextarea.vue")['default']
  CalculatorBreakdownCard: typeof import("../../app/components/calculator/CalculatorBreakdownCard.vue")['default']
  CalculatorQuoteBuilderCard: typeof import("../../app/components/calculator/QuoteBuilderCard.vue")['default']
  ClientActiveJobs: typeof import("../../app/components/client/ClientActiveJobs.vue")['default']
  ClientDashboardSummary: typeof import("../../app/components/client/ClientDashboardSummary.vue")['default']
  ClientQuoteRequests: typeof import("../../app/components/client/ClientQuoteRequests.vue")['default']
  ClientWorkspaceShell: typeof import("../../app/components/client/ClientWorkspaceShell.vue")['default']
  DashboardActionBar: typeof import("../../app/components/dashboard/DashboardActionBar.vue")['default']
  DashboardCardGrid: typeof import("../../app/components/dashboard/DashboardCardGrid.vue")['default']
  DashboardDataTable: typeof import("../../app/components/dashboard/DashboardDataTable.vue")['default']
  DashboardDetailPanel: typeof import("../../app/components/dashboard/DashboardDetailPanel.vue")['default']
  DashboardEmptyState: typeof import("../../app/components/dashboard/DashboardEmptyState.vue")['default']
  DashboardFilterBar: typeof import("../../app/components/dashboard/DashboardFilterBar.vue")['default']
  DashboardMessagePanel: typeof import("../../app/components/dashboard/DashboardMessagePanel.vue")['default']
  DashboardPageHeader: typeof import("../../app/components/dashboard/DashboardPageHeader.vue")['default']
  DashboardSection: typeof import("../../app/components/dashboard/DashboardSection.vue")['default']
  DashboardTimeline: typeof import("../../app/components/dashboard/DashboardTimeline.vue")['default']
  DashboardRoleDashboardFrame: typeof import("../../app/components/dashboard/RoleDashboardFrame.vue")['default']
  DashboardStatusBadge: typeof import("../../app/components/dashboard/StatusBadge.vue")['default']
  FormsFormField: typeof import("../../app/components/forms/FormField.vue")['default']
  JobsFileAttachmentList: typeof import("../../app/components/jobs/FileAttachmentList.vue")['default']
  JobsJobDetailPanel: typeof import("../../app/components/jobs/JobDetailPanel.vue")['default']
  JobsJobSummaryCard: typeof import("../../app/components/jobs/JobSummaryCard.vue")['default']
  JobsProofReviewPanel: typeof import("../../app/components/jobs/ProofReviewPanel.vue")['default']
  JobsProofUploadPanel: typeof import("../../app/components/jobs/ProofUploadPanel.vue")['default']
  JobsPublicJobMetaCard: typeof import("../../app/components/jobs/PublicJobMetaCard.vue")['default']
  JobsQuoteResponsePanel: typeof import("../../app/components/jobs/QuoteResponsePanel.vue")['default']
  JobsShopJobTicketCard: typeof import("../../app/components/jobs/ShopJobTicketCard.vue")['default']
  JobsStatusActionCard: typeof import("../../app/components/jobs/StatusActionCard.vue")['default']
  JobsTrackJobNextActionCard: typeof import("../../app/components/jobs/TrackJobNextActionCard.vue")['default']
  JobsTrackJobStatusCard: typeof import("../../app/components/jobs/TrackJobStatusCard.vue")['default']
  LayoutAuthShell: typeof import("../../app/components/layout/AuthShell.vue")['default']
  LayoutDashboardShell: typeof import("../../app/components/layout/DashboardShell.vue")['default']
  LayoutDashboardSidebar: typeof import("../../app/components/layout/DashboardSidebar.vue")['default']
  LayoutDashboardTopbar: typeof import("../../app/components/layout/DashboardTopbar.vue")['default']
  LayoutPublicShell: typeof import("../../app/components/layout/PublicShell.vue")['default']
  MarketingHomeHeroCalculator: typeof import("../../app/components/marketing/HomeHeroCalculator.vue")['default']
  MarketingPublicFooter: typeof import("../../app/components/marketing/PublicFooter.vue")['default']
  MarketingPublicHeader: typeof import("../../app/components/marketing/PublicHeader.vue")['default']
  MessagesMessageBubble: typeof import("../../app/components/messages/MessageBubble.vue")['default']
  MessagesMessageComposer: typeof import("../../app/components/messages/MessageComposer.vue")['default']
  MessagesQuoteMessageThread: typeof import("../../app/components/messages/QuoteMessageThread.vue")['default']
  PagesClientDashboardClientCurrentJobHero: typeof import("../../app/components/pages/client-dashboard/ClientCurrentJobHero.vue")['default']
  PagesClientDashboardClientReorderPanel: typeof import("../../app/components/pages/client-dashboard/ClientReorderPanel.vue")['default']
  PagesShopWorkspaceShopClientPanel: typeof import("../../app/components/pages/shop-workspace/ShopClientPanel.vue")['default']
  PagesShopWorkspaceShopEarningsPanel: typeof import("../../app/components/pages/shop-workspace/ShopEarningsPanel.vue")['default']
  PagesShopWorkspaceShopProductionBoard: typeof import("../../app/components/pages/shop-workspace/ShopProductionBoard.vue")['default']
  PagesShopWorkspaceShopQuickQuotePanel: typeof import("../../app/components/pages/shop-workspace/ShopQuickQuotePanel.vue")['default']
  PaymentsMpesaPaymentStatusCard: typeof import("../../app/components/payments/MpesaPaymentStatusCard.vue")['default']
  PrintyLogo: typeof import("../../app/components/printy/PrintyLogo.vue")['default']
  ShopsForShopsRateCardBuilder: typeof import("../../app/components/shops/ForShopsRateCardBuilder.vue")['default']
  ShopsRatePreviewPanel: typeof import("../../app/components/shops/RatePreviewPanel.vue")['default']
  ShopsShopIncomingJobsTable: typeof import("../../app/components/shops/ShopIncomingJobsTable.vue")['default']
  ShopsShopJobQueueSummary: typeof import("../../app/components/shops/ShopJobQueueSummary.vue")['default']
  UiDashboardSidebar: typeof import("../../app/components/ui/DashboardSidebar.vue")['default']
  UiDashboardTopbar: typeof import("../../app/components/ui/DashboardTopbar.vue")['default']
  UiDataTableShell: typeof import("../../app/components/ui/DataTableShell.vue")['default']
  UiMetricCard: typeof import("../../app/components/ui/MetricCard.vue")['default']
  UiMoneyText: typeof import("../../app/components/ui/MoneyText.vue")['default']
  UiStatusBadge: typeof import("../../app/components/ui/StatusBadge.vue")['default']
  UiTimeline: typeof import("../../app/components/ui/Timeline.vue")['default']
  UiBadge: typeof import("../../app/components/ui/UiBadge.vue")['default']
  UiButton: typeof import("../../app/components/ui/UiButton.vue")['default']
  UiCard: typeof import("../../app/components/ui/UiCard.vue")['default']
  UiEmptyState: typeof import("../../app/components/ui/UiEmptyState.vue")['default']
  UiErrorState: typeof import("../../app/components/ui/UiErrorState.vue")['default']
  UiInput: typeof import("../../app/components/ui/UiInput.vue")['default']
  UiLoadingSkeleton: typeof import("../../app/components/ui/UiLoadingSkeleton.vue")['default']
  UiSelect: typeof import("../../app/components/ui/UiSelect.vue")['default']
  UiTextarea: typeof import("../../app/components/ui/UiTextarea.vue")['default']
  UploadsArtworkUploadCard: typeof import("../../app/components/uploads/ArtworkUploadCard.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAuthPanel: LazyComponent<typeof import("../../app/components/auth/AuthPanel.vue")['default']>
  LazyBaseAlert: LazyComponent<typeof import("../../app/components/base/BaseAlert.vue")['default']>
  LazyBaseBadge: LazyComponent<typeof import("../../app/components/base/BaseBadge.vue")['default']>
  LazyBaseButton: LazyComponent<typeof import("../../app/components/base/BaseButton.vue")['default']>
  LazyBaseCard: LazyComponent<typeof import("../../app/components/base/BaseCard.vue")['default']>
  LazyBaseContainer: LazyComponent<typeof import("../../app/components/base/BaseContainer.vue")['default']>
  LazyBaseInput: LazyComponent<typeof import("../../app/components/base/BaseInput.vue")['default']>
  LazyBasePage: LazyComponent<typeof import("../../app/components/base/BasePage.vue")['default']>
  LazyBaseSection: LazyComponent<typeof import("../../app/components/base/BaseSection.vue")['default']>
  LazyBaseSelect: LazyComponent<typeof import("../../app/components/base/BaseSelect.vue")['default']>
  LazyBaseStatCard: LazyComponent<typeof import("../../app/components/base/BaseStatCard.vue")['default']>
  LazyBaseTable: LazyComponent<typeof import("../../app/components/base/BaseTable.vue")['default']>
  LazyBaseTextarea: LazyComponent<typeof import("../../app/components/base/BaseTextarea.vue")['default']>
  LazyCalculatorBreakdownCard: LazyComponent<typeof import("../../app/components/calculator/CalculatorBreakdownCard.vue")['default']>
  LazyCalculatorQuoteBuilderCard: LazyComponent<typeof import("../../app/components/calculator/QuoteBuilderCard.vue")['default']>
  LazyClientActiveJobs: LazyComponent<typeof import("../../app/components/client/ClientActiveJobs.vue")['default']>
  LazyClientDashboardSummary: LazyComponent<typeof import("../../app/components/client/ClientDashboardSummary.vue")['default']>
  LazyClientQuoteRequests: LazyComponent<typeof import("../../app/components/client/ClientQuoteRequests.vue")['default']>
  LazyClientWorkspaceShell: LazyComponent<typeof import("../../app/components/client/ClientWorkspaceShell.vue")['default']>
  LazyDashboardActionBar: LazyComponent<typeof import("../../app/components/dashboard/DashboardActionBar.vue")['default']>
  LazyDashboardCardGrid: LazyComponent<typeof import("../../app/components/dashboard/DashboardCardGrid.vue")['default']>
  LazyDashboardDataTable: LazyComponent<typeof import("../../app/components/dashboard/DashboardDataTable.vue")['default']>
  LazyDashboardDetailPanel: LazyComponent<typeof import("../../app/components/dashboard/DashboardDetailPanel.vue")['default']>
  LazyDashboardEmptyState: LazyComponent<typeof import("../../app/components/dashboard/DashboardEmptyState.vue")['default']>
  LazyDashboardFilterBar: LazyComponent<typeof import("../../app/components/dashboard/DashboardFilterBar.vue")['default']>
  LazyDashboardMessagePanel: LazyComponent<typeof import("../../app/components/dashboard/DashboardMessagePanel.vue")['default']>
  LazyDashboardPageHeader: LazyComponent<typeof import("../../app/components/dashboard/DashboardPageHeader.vue")['default']>
  LazyDashboardSection: LazyComponent<typeof import("../../app/components/dashboard/DashboardSection.vue")['default']>
  LazyDashboardTimeline: LazyComponent<typeof import("../../app/components/dashboard/DashboardTimeline.vue")['default']>
  LazyDashboardRoleDashboardFrame: LazyComponent<typeof import("../../app/components/dashboard/RoleDashboardFrame.vue")['default']>
  LazyDashboardStatusBadge: LazyComponent<typeof import("../../app/components/dashboard/StatusBadge.vue")['default']>
  LazyFormsFormField: LazyComponent<typeof import("../../app/components/forms/FormField.vue")['default']>
  LazyJobsFileAttachmentList: LazyComponent<typeof import("../../app/components/jobs/FileAttachmentList.vue")['default']>
  LazyJobsJobDetailPanel: LazyComponent<typeof import("../../app/components/jobs/JobDetailPanel.vue")['default']>
  LazyJobsJobSummaryCard: LazyComponent<typeof import("../../app/components/jobs/JobSummaryCard.vue")['default']>
  LazyJobsProofReviewPanel: LazyComponent<typeof import("../../app/components/jobs/ProofReviewPanel.vue")['default']>
  LazyJobsProofUploadPanel: LazyComponent<typeof import("../../app/components/jobs/ProofUploadPanel.vue")['default']>
  LazyJobsPublicJobMetaCard: LazyComponent<typeof import("../../app/components/jobs/PublicJobMetaCard.vue")['default']>
  LazyJobsQuoteResponsePanel: LazyComponent<typeof import("../../app/components/jobs/QuoteResponsePanel.vue")['default']>
  LazyJobsShopJobTicketCard: LazyComponent<typeof import("../../app/components/jobs/ShopJobTicketCard.vue")['default']>
  LazyJobsStatusActionCard: LazyComponent<typeof import("../../app/components/jobs/StatusActionCard.vue")['default']>
  LazyJobsTrackJobNextActionCard: LazyComponent<typeof import("../../app/components/jobs/TrackJobNextActionCard.vue")['default']>
  LazyJobsTrackJobStatusCard: LazyComponent<typeof import("../../app/components/jobs/TrackJobStatusCard.vue")['default']>
  LazyLayoutAuthShell: LazyComponent<typeof import("../../app/components/layout/AuthShell.vue")['default']>
  LazyLayoutDashboardShell: LazyComponent<typeof import("../../app/components/layout/DashboardShell.vue")['default']>
  LazyLayoutDashboardSidebar: LazyComponent<typeof import("../../app/components/layout/DashboardSidebar.vue")['default']>
  LazyLayoutDashboardTopbar: LazyComponent<typeof import("../../app/components/layout/DashboardTopbar.vue")['default']>
  LazyLayoutPublicShell: LazyComponent<typeof import("../../app/components/layout/PublicShell.vue")['default']>
  LazyMarketingHomeHeroCalculator: LazyComponent<typeof import("../../app/components/marketing/HomeHeroCalculator.vue")['default']>
  LazyMarketingPublicFooter: LazyComponent<typeof import("../../app/components/marketing/PublicFooter.vue")['default']>
  LazyMarketingPublicHeader: LazyComponent<typeof import("../../app/components/marketing/PublicHeader.vue")['default']>
  LazyMessagesMessageBubble: LazyComponent<typeof import("../../app/components/messages/MessageBubble.vue")['default']>
  LazyMessagesMessageComposer: LazyComponent<typeof import("../../app/components/messages/MessageComposer.vue")['default']>
  LazyMessagesQuoteMessageThread: LazyComponent<typeof import("../../app/components/messages/QuoteMessageThread.vue")['default']>
  LazyPagesClientDashboardClientCurrentJobHero: LazyComponent<typeof import("../../app/components/pages/client-dashboard/ClientCurrentJobHero.vue")['default']>
  LazyPagesClientDashboardClientReorderPanel: LazyComponent<typeof import("../../app/components/pages/client-dashboard/ClientReorderPanel.vue")['default']>
  LazyPagesShopWorkspaceShopClientPanel: LazyComponent<typeof import("../../app/components/pages/shop-workspace/ShopClientPanel.vue")['default']>
  LazyPagesShopWorkspaceShopEarningsPanel: LazyComponent<typeof import("../../app/components/pages/shop-workspace/ShopEarningsPanel.vue")['default']>
  LazyPagesShopWorkspaceShopProductionBoard: LazyComponent<typeof import("../../app/components/pages/shop-workspace/ShopProductionBoard.vue")['default']>
  LazyPagesShopWorkspaceShopQuickQuotePanel: LazyComponent<typeof import("../../app/components/pages/shop-workspace/ShopQuickQuotePanel.vue")['default']>
  LazyPaymentsMpesaPaymentStatusCard: LazyComponent<typeof import("../../app/components/payments/MpesaPaymentStatusCard.vue")['default']>
  LazyPrintyLogo: LazyComponent<typeof import("../../app/components/printy/PrintyLogo.vue")['default']>
  LazyShopsForShopsRateCardBuilder: LazyComponent<typeof import("../../app/components/shops/ForShopsRateCardBuilder.vue")['default']>
  LazyShopsRatePreviewPanel: LazyComponent<typeof import("../../app/components/shops/RatePreviewPanel.vue")['default']>
  LazyShopsShopIncomingJobsTable: LazyComponent<typeof import("../../app/components/shops/ShopIncomingJobsTable.vue")['default']>
  LazyShopsShopJobQueueSummary: LazyComponent<typeof import("../../app/components/shops/ShopJobQueueSummary.vue")['default']>
  LazyUiDashboardSidebar: LazyComponent<typeof import("../../app/components/ui/DashboardSidebar.vue")['default']>
  LazyUiDashboardTopbar: LazyComponent<typeof import("../../app/components/ui/DashboardTopbar.vue")['default']>
  LazyUiDataTableShell: LazyComponent<typeof import("../../app/components/ui/DataTableShell.vue")['default']>
  LazyUiMetricCard: LazyComponent<typeof import("../../app/components/ui/MetricCard.vue")['default']>
  LazyUiMoneyText: LazyComponent<typeof import("../../app/components/ui/MoneyText.vue")['default']>
  LazyUiStatusBadge: LazyComponent<typeof import("../../app/components/ui/StatusBadge.vue")['default']>
  LazyUiTimeline: LazyComponent<typeof import("../../app/components/ui/Timeline.vue")['default']>
  LazyUiBadge: LazyComponent<typeof import("../../app/components/ui/UiBadge.vue")['default']>
  LazyUiButton: LazyComponent<typeof import("../../app/components/ui/UiButton.vue")['default']>
  LazyUiCard: LazyComponent<typeof import("../../app/components/ui/UiCard.vue")['default']>
  LazyUiEmptyState: LazyComponent<typeof import("../../app/components/ui/UiEmptyState.vue")['default']>
  LazyUiErrorState: LazyComponent<typeof import("../../app/components/ui/UiErrorState.vue")['default']>
  LazyUiInput: LazyComponent<typeof import("../../app/components/ui/UiInput.vue")['default']>
  LazyUiLoadingSkeleton: LazyComponent<typeof import("../../app/components/ui/UiLoadingSkeleton.vue")['default']>
  LazyUiSelect: LazyComponent<typeof import("../../app/components/ui/UiSelect.vue")['default']>
  LazyUiTextarea: LazyComponent<typeof import("../../app/components/ui/UiTextarea.vue")['default']>
  LazyUploadsArtworkUploadCard: LazyComponent<typeof import("../../app/components/uploads/ArtworkUploadCard.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
