<template>
  <div class="quote-document-shell space-y-6">
    <div class="quote-document-actions flex flex-wrap items-center justify-between gap-3">
      <BaseButton variant="outline" size="sm" :to="backTo">
        <Icon name="lucide:arrow-left" class="mr-1.5 size-4" />
        {{ backLabel }}
      </BaseButton>

      <div class="flex flex-wrap gap-2">
        <BaseButton variant="outline" size="sm" @click="copyLink">
          <Icon name="lucide:link" class="mr-1.5 size-4" />
          {{ copied ? 'Link copied' : 'Share link' }}
        </BaseButton>
        <BaseButton variant="primary" size="sm" @click="printDocument">
          <Icon name="lucide:printer" class="mr-1.5 size-4" />
          Print
        </BaseButton>
      </div>
    </div>

    <div class="rounded-[32px] border border-[var(--p-border)] bg-[var(--p-surface)] p-6 shadow-sm print:rounded-none print:border-0 print:p-0 print:shadow-none">
      <div class="flex flex-col gap-6 border-b border-[var(--p-border)] pb-6 md:flex-row md:items-start md:justify-between">
        <div class="space-y-4">
          <div class="flex items-center gap-4">
            <div class="flex size-14 items-center justify-center rounded-2xl bg-[var(--p-primary)]/10 text-lg font-black text-[var(--p-primary)]">
              {{ initials }}
            </div>
            <div>
              <p class="text-xs font-bold uppercase tracking-[0.24em] text-[var(--p-text-muted)]">Generated by Printy</p>
              <h1 class="text-3xl font-black tracking-tight text-[var(--p-text)]">{{ document.shopName }}</h1>
            </div>
          </div>
          <p class="max-w-2xl text-sm leading-6 text-[var(--p-text-muted)]">
            Professional quote summary for buyer-safe review, printing, and later PDF export.
          </p>
        </div>

        <div class="grid gap-3 rounded-3xl bg-[var(--p-bg-soft)] p-5 sm:grid-cols-2">
          <div>
            <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Quote number</p>
            <p class="mt-1 text-sm font-semibold text-[var(--p-text)]">{{ document.quoteNumber }}</p>
          </div>
          <div>
            <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Quote date</p>
            <p class="mt-1 text-sm font-semibold text-[var(--p-text)]">{{ document.quoteDate }}</p>
          </div>
          <div>
            <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Status</p>
            <p class="mt-1 text-sm font-semibold text-[var(--p-text)]">{{ document.quoteStatus }}</p>
          </div>
          <div>
            <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Currency</p>
            <p class="mt-1 text-sm font-semibold text-[var(--p-text)]">{{ document.currency }}</p>
          </div>
        </div>
      </div>

      <div class="mt-6 grid gap-4 lg:grid-cols-2">
        <section class="rounded-3xl bg-[var(--p-bg-soft)] p-5">
          <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Prepared by</p>
          <h2 class="mt-2 text-lg font-bold text-[var(--p-text)]">{{ document.shopName }}</h2>
          <ul class="mt-3 space-y-2 text-sm text-[var(--p-text-muted)]">
            <li v-for="entry in document.shopContact" :key="entry">{{ entry }}</li>
            <li v-if="!document.shopContact.length">Public contact not listed.</li>
          </ul>
        </section>

        <section class="rounded-3xl bg-[var(--p-bg-soft)] p-5">
          <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Prepared for</p>
          <h2 class="mt-2 text-lg font-bold text-[var(--p-text)]">{{ document.clientName }}</h2>
          <ul class="mt-3 space-y-2 text-sm text-[var(--p-text-muted)]">
            <li v-for="entry in document.clientContact" :key="entry">{{ entry }}</li>
            <li v-if="!document.clientContact.length">Contact details not shown.</li>
          </ul>
        </section>
      </div>

      <div class="mt-6 grid gap-4 xl:grid-cols-[1.2fr_0.8fr]">
        <section class="rounded-3xl border border-[var(--p-border)] p-5">
          <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Job description</p>
          <p class="mt-3 text-lg font-semibold text-[var(--p-text)]">{{ document.jobDescription }}</p>
          <p class="mt-3 text-sm leading-6 text-[var(--p-text-muted)]">{{ document.notes }}</p>
          <div class="mt-4 rounded-2xl bg-[var(--p-bg-soft)] p-4 text-sm text-[var(--p-text-muted)]">
            <span class="font-semibold text-[var(--p-text)]">Artwork summary:</span>
            {{ document.artworkSummary }}
          </div>
        </section>

        <section class="rounded-3xl border border-[var(--p-border)] p-5">
          <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Production preview</p>
          <div class="mt-4 grid gap-3 sm:grid-cols-2">
            <div
              v-for="item in document.productionPreview"
              :key="item.label"
              class="rounded-2xl bg-[var(--p-bg-soft)] p-4"
            >
              <p class="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--p-text-muted)]">{{ item.label }}</p>
              <p class="mt-2 text-sm font-semibold text-[var(--p-text)]">{{ item.value }}</p>
            </div>
          </div>
        </section>
      </div>

      <section class="mt-6 rounded-3xl border border-[var(--p-border)] p-5">
        <div class="flex items-center justify-between gap-3">
          <div>
            <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Quote line items</p>
            <p class="mt-1 text-sm text-[var(--p-text-muted)]">Only buyer-safe pricing is shown here.</p>
          </div>
          <div class="rounded-full bg-[var(--p-primary)]/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.14em] text-[var(--p-primary)]">
            Printable HTML
          </div>
        </div>

        <div class="mt-5 overflow-x-auto">
          <table class="min-w-full border-separate border-spacing-0">
            <thead>
              <tr class="text-left text-[11px] uppercase tracking-[0.18em] text-[var(--p-text-muted)]">
                <th class="border-b border-[var(--p-border)] px-3 py-3">Description</th>
                <th class="border-b border-[var(--p-border)] px-3 py-3">Quantity</th>
                <th class="border-b border-[var(--p-border)] px-3 py-3">Unit price</th>
                <th class="border-b border-[var(--p-border)] px-3 py-3 text-right">Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="item in document.lineItems"
                :key="`${item.description}-${item.quantity}-${item.amount}`"
                class="text-sm text-[var(--p-text)]"
              >
                <td class="border-b border-[var(--p-border)] px-3 py-4 font-medium">{{ item.description }}</td>
                <td class="border-b border-[var(--p-border)] px-3 py-4 text-[var(--p-text-muted)]">{{ item.quantity }}</td>
                <td class="border-b border-[var(--p-border)] px-3 py-4 text-[var(--p-text-muted)]">{{ item.unitPrice }}</td>
                <td class="border-b border-[var(--p-border)] px-3 py-4 text-right font-semibold">{{ item.amount }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <div class="mt-6 grid gap-4 xl:grid-cols-[1fr_360px]">
        <section class="rounded-3xl border border-[var(--p-border)] p-5">
          <p class="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--p-text-muted)]">Delivery and validity</p>
          <div class="mt-4 grid gap-3 sm:grid-cols-2">
            <div class="rounded-2xl bg-[var(--p-bg-soft)] p-4">
              <p class="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--p-text-muted)]">Turnaround</p>
              <p class="mt-2 text-sm font-semibold text-[var(--p-text)]">{{ document.turnaround }}</p>
            </div>
            <div class="rounded-2xl bg-[var(--p-bg-soft)] p-4">
              <p class="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--p-text-muted)]">Validity / expiry</p>
              <p class="mt-2 text-sm font-semibold text-[var(--p-text)]">{{ document.validity }}</p>
            </div>
          </div>
        </section>

        <section class="rounded-3xl bg-slate-950 p-5 text-white">
          <div class="space-y-3 text-sm">
            <div class="flex items-center justify-between gap-3">
              <span class="text-slate-300">Subtotal</span>
              <span class="font-semibold">{{ document.subtotal }}</span>
            </div>
            <div class="flex items-center justify-between gap-3">
              <span class="text-slate-300">Discounts</span>
              <span class="font-semibold">{{ document.discounts }}</span>
            </div>
            <div class="flex items-center justify-between gap-3 border-t border-white/10 pt-3 text-lg font-black">
              <span>Total</span>
              <span>{{ document.total }}</span>
            </div>
          </div>
        </section>
      </div>

      <div class="mt-6 rounded-3xl bg-[var(--p-bg-soft)] px-5 py-4 text-sm text-[var(--p-text-muted)]">
        {{ document.footerNote }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { QuoteDocumentModel } from '~/utils/quoteDocument'

const props = withDefaults(defineProps<{
  document: QuoteDocumentModel
  backTo: string
  backLabel?: string
}>(), {
  backLabel: 'Back',
})

const route = useRoute()
const copied = ref(false)

const initials = computed(() => {
  const source = props.document.shopName || 'Printy'
  return source.split(/\s+/).slice(0, 2).map(part => part.charAt(0).toUpperCase()).join('')
})

function printDocument() {
  if (import.meta.client) window.print()
}

async function copyLink() {
  if (!import.meta.client) return
  try {
    await navigator.clipboard.writeText(window.location.origin + route.fullPath)
    copied.value = true
    window.setTimeout(() => {
      copied.value = false
    }, 1800)
  } catch {
    copied.value = false
  }
}
</script>

<style scoped>
@media print {
  :global(aside),
  :global(nav),
  :global(header),
  .quote-document-actions {
    display: none !important;
  }

  .quote-document-shell {
    padding: 0 !important;
  }
}
</style>
