export const API = {
  auth: {
    register: '/auth/register/',
    registerClient: '/auth/register/client/',
    registerPartner: '/auth/register/partner/',
    registerProduction: '/auth/register/production/',
    login: '/auth/token/',
    refresh: '/auth/token/refresh/',
    me: '/auth/me/',
    confirmEmail: '/auth/confirm-email/',
    resendConfirmation: '/auth/resend-confirmation/',
    forgotPassword: '/auth/password-reset/',
    resetConfirm: '/auth/password-reset/confirm/',
  },
  calculator: {
    config: '/calculator/config/',
    publicPreview: '/calculator/public-preview/',
    dashboardPreview: '/dashboard/calculator/preview/',
  },
  dashboard: {
    adminHome: '/dashboard/admin/',
    clientHome: '/dashboard/client-home/',
    partnerHome: '/dashboard/partner-home/',
    productionHome: '/dashboard/production-home/',
    clientQuotes: '/dashboard/client/quotes/',
    clientQuoteDetail: (id: number | string) => `/dashboard/client/quotes/${id}/`,
    clientJobs: '/dashboard/client/jobs/',
    clientJobDetail: (id: number | string) => `/dashboard/client/jobs/${id}/`,
    clientPayments: '/dashboard/client/payments/',
    partnerQuotes: '/dashboard/partner/quotes/',
    partnerQuoteDetail: (id: number | string) => `/dashboard/partner/quotes/${id}/`,
    partnerQuoteSendToClient: (id: number | string) => `/dashboard/partner/quotes/${id}/send-to-client/`,
    partnerJobs: '/dashboard/partner/jobs/',
    partnerJobDetail: (id: number | string) => `/dashboard/partner/jobs/${id}/`,
    partnerJobDispatch: (id: number | string) => `/dashboard/partner/jobs/${id}/dispatch/`,
    partnerClients: '/dashboard/partner/clients/',
    partnerProductionShops: '/dashboard/partner/production-shops/',
    partnerPayments: '/dashboard/partner/payments/',
    productionJobs: '/dashboard/production/jobs/',
    productionJobDetail: (id: number | string) => `/dashboard/production/jobs/${id}/`,
    productionPricing: '/dashboard/production/pricing/',
    productionPaperStock: '/dashboard/production/paper-stock/',
    productionFinishings: '/dashboard/production/finishings/',
    productionPayments: '/dashboard/production/payments/',
  },
  jobs: {
    publicManagedTrack: (token: string) => `/public/managed-jobs/track/${token}/`,
    publicTrack: (token: string) => `/public/job/${token}/`,
    managedJobs: '/managed-jobs/',
    shopAssignments: '/shop/assignments/',
    managedJobFiles: (id: number | string) => `/managed-jobs/${id}/files/`,
    managedJobEvents: (id: number | string) => `/managed-jobs/${id}/events/`,
    managedJobPayments: (id: number | string) => `/managed-jobs/${id}/payments/`,
    managedJobSettlement: (id: number | string) => `/managed-jobs/${id}/settlement/`,
    managedJobStkPush: (id: number | string) => `/managed-jobs/${id}/payments/mpesa/stk-push/`,
    managedJobPaymentQuery: (id: number | string) => `/managed-jobs/${id}/payments/mpesa/query/`,
    managedJobProofUpload: (id: number | string) => `/managed-jobs/${id}/files/proofs/`,
    assignmentAccept: (id: number | string) => `/job-assignments/${id}/accept/`,
    assignmentReject: (id: number | string) => `/job-assignments/${id}/reject/`,
    assignmentInProduction: (id: number | string) => `/job-assignments/${id}/mark-in-production/`,
    assignmentReady: (id: number | string) => `/job-assignments/${id}/mark-ready/`,
    assignmentCompleted: (id: number | string) => `/job-assignments/${id}/mark-completed/`,
    assignmentReportIssue: (id: number | string) => `/job-assignments/${id}/report-issue/`,
    jobFileApprove: (id: number | string) => `/job-files/${id}/approve/`,
    jobFileReject: (id: number | string) => `/job-files/${id}/reject/`,
    jobFileRequestRevision: (id: number | string) => `/job-files/${id}/request-revision/`,
  },
  workflow: {
    quoteRequests: '/workflow/quote-requests/',
    clientResponses: '/client/responses/',
    clientRequestDetail: (id: number | string) => `/client/requests/${id}/`,
    shopRequestDetail: (id: number | string) => `/shop/requests/${id}/`,
    requestResponses: (id: number | string) => `/quote-requests/${id}/responses/`,
    clientAcceptResponse: (id: number | string) => `/client/responses/${id}/accept/`,
    clientRejectResponse: (id: number | string) => `/client/responses/${id}/reject/`,
    clientReplyResponse: (id: number | string) => `/client/responses/${id}/reply/`,
    shopReplyResponse: (id: number | string) => `/shop/responses/${id}/reply/`,
    dashboardShopHome: '/dashboard/shop-home/',
  },
  quoteRequests: {
    list: '/quote-requests/',
    detail: (id: number | string) => `/quote-requests/${id}/`,
    submit: (id: number | string) => `/quote-requests/${id}/submit/`,
    accept: (id: number | string) => `/quote-requests/${id}/accept/`,
    reply: (id: number | string) => `/quote-requests/${id}/reply/`,
    attachments: (id: number | string) => `/quote-requests/${id}/attachments/`,
  },
  quoteDrafts: {
    list: '/calculator/drafts/',
    detail: (id: number | string) => `/calculator/drafts/${id}/`,
    send: (id: number | string) => `/calculator/drafts/${id}/send/`,
  },
  partner: {
    quotes: '/partner/quotes/',
    quotePreview: '/partner/quotes/preview/',
    quoteCreate: '/partner/quotes/create/',
    clients: '/dashboard/partner/clients/',
  },
  messages: {
    client: '/client/messages/',
    shop: '/shop/messages/',
  },
  forShops: {
    publicConfig: '/for-shops/rate-card/public-config/',
    publicPreview: '/for-shops/rate-card/public-preview/',
    save: '/for-shops/rate-card/save/',
    setup: '/shops/rate-card/setup/',
    complete: '/shops/rate-card/onboarding-complete/',
  },
  notifications: '/me/notifications/',
} as const
