// Purpose: Restored API path map with endpoint signatures shaped to surviving callers.
type PathPart = string | number | null | undefined

const clean = (value: PathPart) => String(value ?? '').replace(/^\/+|\/+$/g, '')
const join = (...parts: PathPart[]) => `/${parts.map(clean).filter(Boolean).join('/')}/`

const one = (...prefix: PathPart[]) => (a?: PathPart) => join(...prefix, a)
const two = (...prefix: PathPart[]) => (a?: PathPart, b?: PathPart) => join(...prefix, a, b)
const three = (...prefix: PathPart[]) => (a?: PathPart, b?: PathPart, c?: PathPart) => join(...prefix, a, b, c)
const noArg = (...prefix: PathPart[]) => () => join(...prefix)

export const API = {
  auth: {
    token: join('auth', 'token'),
    tokenRefresh: join('auth', 'token', 'refresh'),
    me: join('auth', 'me'),
    register: join('auth', 'register'),
    emailVerify: join('auth', 'email', 'verify'),
    emailResend: join('auth', 'email', 'resend'),
    forgotPassword: join('auth', 'forgot-password'),
    resetConfirm: join('auth', 'reset-confirm'),
  },

  adminAnalyticsErrors: noArg('admin', 'analytics', 'errors'),
  adminAnalyticsFunnel: noArg('admin', 'analytics', 'funnel'),
  adminAnalyticsLocations: noArg('admin', 'analytics', 'locations'),
  adminAnalyticsSummary: noArg('admin', 'analytics', 'summary'),
  adminAnalyticsTimeSeries: noArg('admin', 'analytics', 'time-series'),
  adminAnalyticsTopMetrics: noArg('admin', 'analytics', 'top-metrics'),
  analyticsEvents: noArg('analytics', 'events'),

  artworkUpload: noArg('artwork', 'upload'),
  artworkDetail: one('artwork'),

  billingCancel: noArg('billing', 'cancel'),
  billingDowngrade: noArg('billing', 'downgrade'),
  billingInitiateRenewal: noArg('billing', 'renew'),
  billingPayments: noArg('billing', 'payments'),
  billingPlans: noArg('billing', 'plans'),
  billingReactivate: noArg('billing', 'reactivate'),
  billingSubscribe: noArg('billing', 'subscribe'),
  billingSubscription: noArg('billing', 'subscription'),
  billingUpgrade: noArg('billing', 'upgrade'),
  billingUsage: noArg('billing', 'usage'),

  calculatorDrafts: noArg('calculator', 'drafts'),
  calculatorDraftDetail: one('calculator', 'drafts'),
  calculatorDraftSend: (draftId?: PathPart) => join('calculator', 'drafts', draftId, 'send'),

  // Calculator endpoints:
  // GET  /api/calculator/config/
  // POST /api/calculator/public-preview/
  // POST /api/calculator/preview/
  // POST /api/calculator/booklet-preview/
  // POST /api/calculator/large-format-preview/
  calculatorConfig: noArg('calculator', 'config'),
  calculatorPublicPreview: noArg('calculator', 'public-preview'),
  calculatorPreview: noArg('calculator', 'preview'),
  bookletCalculatorPreview: noArg('calculator', 'booklet-preview'),
  calculatorBookletPreview: noArg('calculator', 'booklet-preview'),
  calculatorLargeFormatPreview: noArg('calculator', 'large-format-preview'),
  calculatorQuoteItem: one('calculator', 'quote-item'),

  claimDetail: one('claims'),
  claimReview: two('claims'),
  claims: noArg('claims'),
  claimVerify: two('claims'),

  dashboardShopHome: noArg('dashboard', 'shop', 'home'),
  finishingCategories: noArg('pricing', 'finishing-categories'),

  machinePrintRates: (machineId?: PathPart) => join('machines', machineId, 'printing-rates'),
  machinePrintRateDetail: (machineId?: PathPart, rateId?: PathPart) => join('machines', machineId, 'printing-rates', rateId),
  shopPricingDiscounts: (shopSlug?: PathPart) => join('shops', shopSlug, 'pricing', 'discounts'),
  shopPricingDiscountDetail: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'pricing', 'discounts', id),

  incomingRequests: (shopSlug?: PathPart) => join('shops', shopSlug, 'incoming-requests'),
  incomingRequestDetail: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId),
  incomingRequestSendQuote: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'send-quote'),
  incomingRequestAccept: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'accept-request'),
  incomingRequestAskQuestion: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'ask-question'),
  incomingRequestReject: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'reject-request'),
  incomingRequestMarkViewed: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'mark-viewed'),
  incomingRequestDecline: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'decline'),
  incomingRequestBrief: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'brief'),
  incomingRequestDownloadPdf: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'download-pdf'),
  incomingRequestWhatsappHandoff: (shopSlug?: PathPart, requestId?: PathPart) => join('shops', shopSlug, 'incoming-requests', requestId, 'whatsapp-handoff'),

  jobClaimAccept: one('job-claims'),
  jobClaimReject: one('job-claims'),
  jobClaims: noArg('job-claims'),
  jobRequestClaims: one('job-requests'),
  jobRequestDetail: one('job-requests'),
  jobRequests: noArg('job-requests'),
  jobRequestWhatsappShare: one('job-requests'),

  meFavoriteDetail: one('me', 'favorites'),
  meFavorites: noArg('me', 'favorites'),
  myQuotes: noArg('me', 'quotes'),

  notificationActivitySummary: noArg('notifications', 'activity-summary'),
  notificationMarkAllRead: noArg('notifications', 'mark-all-read'),
  notificationMarkRead: one('notifications'),
  notifications: noArg('notifications'),
  notificationUnreadCount: noArg('notifications', 'unread-count'),

  plans: noArg('plans'),

  pricingDefaultsFinishing: noArg('pricing', 'defaults', 'finishing'),
  pricingDefaultsMaterials: noArg('pricing', 'defaults', 'materials'),
  pricingDefaultsPapers: noArg('pricing', 'defaults', 'papers'),
  pricingDefaultsPrinting: noArg('pricing', 'defaults', 'printing'),

  profileAvatarUpload: noArg('profiles', 'me', 'avatar'),
  profileDetail: one('profiles'),
  profileMe: noArg('profiles', 'me'),
  profiles: noArg('profiles'),
  profileSocialLinks: one('profiles'),

  publicJob: one('public', 'jobs'),
  publicMatchBookletShops: noArg('public', 'match-booklet-shops'),
  publicMatchShops: noArg('public', 'match-shops'),
  publicShopCalculatorPreview: one('public', 'shops'),
  publicShopCatalog: (shopSlug?: PathPart) => join('public', 'shops', shopSlug, 'catalog'),
  publicShopCustomOptions: (shopSlug?: PathPart) => join('public', 'shops', shopSlug, 'custom-options'),
  publicShopDetail: one('public', 'shops'),
  publicShopRatingSummary: (shopSlug?: PathPart) => join('public', 'shops', shopSlug, 'rating-summary'),
  publicShops: noArg('public', 'shops'),

  quoteDraftDownloadPdf: one('quote-drafts'),
  quoteDraftFileDetail: one('quote-draft-files'),
  quoteDraftFileDownloadPdf: one('quote-draft-files'),
  quoteDraftFiles: noArg('quote-draft-files'),
  quoteDraftFileWhatsappPreview: one('quote-draft-files'),
  quoteDraftItemAttachmentDetail: three('quote-drafts'),
  quoteDraftItemAttachments: two('quote-drafts'),
  quoteDraftItemDetail: two('quote-drafts'),
  quoteDraftItemRequestQuote: two('quote-drafts'),
  quoteDraftItems: one('quote-drafts'),
  quoteDraftPreviewPrice: one('quote-drafts'),
  quoteDraftRequestQuote: one('quote-drafts'),
  quoteDraftsActive: (shopSlug?: PathPart, fileId?: PathPart) => join('quote-drafts', 'active', shopSlug, fileId),
  quoteDraftTweakAndAdd: one('quote-drafts'),

  quoteRequestAccept: (requestId?: PathPart) => join('quote-requests', requestId, 'accept'),
  quoteRequestCancel: (requestId?: PathPart) => join('quote-requests', requestId, 'cancel'),
  quoteRequestDetail: one('quote-requests'),
  quoteRequestReply: (requestId?: PathPart) => join('quote-requests', requestId, 'reply'),
  quoteRequestResponses: (requestId?: PathPart) => join('quote-requests', requestId, 'responses'),
  quoteRequests: noArg('quote-requests'),
  quoteRequestSubmit: (requestId?: PathPart) => join('quote-requests', requestId, 'submit'),
  quoteRequestBrief: (requestId?: PathPart) => join('quote-requests', requestId, 'brief'),
  quoteRequestDownloadPdf: (requestId?: PathPart) => join('quote-requests', requestId, 'download-pdf'),
  quoteRequestWhatsappHandoff: (requestId?: PathPart) => join('quote-requests', requestId, 'whatsapp-handoff'),

  requestQuote: one('shops'),

  sellerMachinePrintingRateDetail: two('seller', 'machine-printing-rates'),
  sellerMachinePrintingRates: one('seller', 'machine-printing-rates'),
  sellerShopDetail: one('seller', 'shops'),
  sellerShopFinishingRateDetail: two('seller', 'shops', 'finishing-rates'),
  sellerShopFinishingRates: one('seller', 'shops', 'finishing-rates'),
  sellerShopMachineDetail: two('seller', 'shops', 'machines'),
  sellerShopMachines: one('seller', 'shops', 'machines'),
  sellerShopMaterialDetail: two('seller', 'shops', 'materials'),
  sellerShopMaterials: one('seller', 'shops', 'materials'),
  sellerShopPaperDetail: two('seller', 'shops', 'papers'),
  sellerShopPapers: one('seller', 'shops', 'papers'),
  sellerShopProductDetail: two('seller', 'shops', 'products'),
  sellerShopProducts: one('seller', 'shops', 'products'),

  sentQuoteDetail: one('sent-quotes'),
  sentQuotes: noArg('sent-quotes'),

  seoLocationDetail: one('seo', 'locations'),
  seoLocationProduct: two('seo', 'locations'),
  seoLocationProducts: one('seo', 'locations'),
  seoLocations: noArg('seo', 'locations'),
  seoProductDetail: one('seo', 'products'),
  seoProducts: noArg('seo', 'products'),
  seoRoutes: noArg('seo', 'routes'),

  setupStatus: noArg('setup-status'),

  shopCalculatePrice: one('shops'),
  shopDetail: one('shops'),
  shopFinishingRateDetail: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'finishing-rates', id),
  shopFinishingRates: (shopSlug?: PathPart) => join('shops', shopSlug, 'finishing-rates'),
  shopFinishingServiceDetail: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'finishing-rates', id),
  shopFinishingServices: (shopSlug?: PathPart) => join('shops', shopSlug, 'finishing-rates'),
  shopHours: (shopSlug?: PathPart) => join('shops', shopSlug, 'hours'),
  shopHoursBulk: (shopSlug?: PathPart) => join('shops', shopSlug, 'hours', 'bulk'),
  shopMachineDetail: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'machines', id),
  shopMachines: (shopSlug?: PathPart) => join('shops', shopSlug, 'machines'),
  shopMaterialDetail: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'materials', id),
  shopMaterialPrices: (shopSlug?: PathPart) => join('shops', shopSlug, 'materials'),
  shopMaterialPriceDetail: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'materials', id),
  shopMaterials: (shopSlug?: PathPart) => join('shops', shopSlug, 'materials'),
  shopMemberDetail: two('shops'),
  shopMembers: one('shops'),
  shopPapers: (shopSlug?: PathPart) => join('shops', shopSlug, 'papers'),
  shopPaper: (shopSlug?: PathPart) => join('shops', shopSlug, 'papers'),
  shopPaperAdjust: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'papers', id, 'adjust'),
  shopPaperDetail: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'papers', id),
  shopPapersDetail: (shopSlug?: PathPart, id?: PathPart) => join('shops', shopSlug, 'papers', id),
  shopPricingSeedDefaults: one('shops'),
  shopPricingStatus: one('shops'),
  shopProductCategories: one('shops'),
  shopProductDetail: two('shops'),
  shopProducts: (shopSlug?: PathPart) => (shopSlug ? join('shops', shopSlug, 'products') : join('products')),
  shopQuoteCalculate: two('shops'),
  shopQuoteDetail: two('shops'),
  shopQuoteDuplicate: two('shops'),
  shopQuoteItemDetail: three('shops'),
  shopQuoteItems: two('shops'),
  shopQuotes: one('shops'),
  shopQuoteUpdateStatus: two('shops'),
  shopRate: one('shops'),
  shopRateCard: (shopSlug?: PathPart) => join('shops', shopSlug, 'rate-card'),
  shopRateCardForCalculator: (shopSlug?: PathPart) => join('shops', shopSlug, 'rate-card-for-calculator'),
  shops: noArg('shops'),
  shopsNearby: noArg('shops', 'nearby'),
  shopSetupStatus: (shopSlug?: PathPart) => join('shops', shopSlug, 'setup-status'),
  shopSocialLinkDetail: two('shops'),
  shopSocialLinks: one('shops'),
  shopSubscription: one('shops'),
  shopTransferOwnership: one('shops'),
  shopVolumeDiscountDetail: two('shops'),
  shopVolumeDiscounts: one('shops'),

  socialLinkDetail: one('social-links'),

  staffQuoteDetail: one('staff', 'quotes'),
  staffQuoteItemDetail: two('staff', 'quote-items'),
  staffQuoteItems: one('staff', 'quote-items'),
  staffQuotes: noArg('staff', 'quotes'),
  staffQuoteSend: one('staff', 'quotes'),
  staffQuoteWhatsappPreview: one('staff', 'quotes'),

  tweakedItemDetail: one('tweaked-items'),

  userDetail: one('users'),
  userMe: noArg('users', 'me'),
  users: noArg('users'),
}