export const API = {
  notifications: {
    list: '/me/notifications/',
    unreadCount: '/me/notifications/unread-count/',
    markRead: (id: number | string) => `/me/notifications/${id}/mark-read/`,
    markAllRead: '/me/notifications/mark-all-read/',
  },
  auth: {
    register: '/auth/register/',
    login: '/auth/login/',
    refresh: '/auth/token/refresh/',
    me: '/auth/me/',
    confirmEmail: '/auth/confirm-email/',
    resendConfirmation: '/auth/resend-confirmation/',
    forgotPassword: '/auth/password-reset/',
    resetConfirm: '/auth/password-reset/confirm/',
    changePassword: '/auth/password-change/',
  },
  jobs: {
    publicManagedTrack: (token: string) => `/public/managed-jobs/track/${token}/`,
  },
  profile: {
    me: '/profiles/me/',
    avatar: '/profiles/me/avatar/',
  },
  rateCard: {
    setup: '/shops/rate-card/setup/',
    complete: '/shops/rate-card/onboarding-complete/',
    publicConfig: '/for-shops/rate-card/public-config/',
    publicPreview: '/for-shops/rate-card/public-preview/',
    save: '/for-shops/rate-card/save/',
  },
  shop: {
    list: '/shops/',
    detail: (shop: number | string) => `/shops/${shop}/`,
    papers: (shop: number | string) => `/shops/${shop}/papers/`,
    paper: (shop: number | string, id: number | string) => `/shops/${shop}/papers/${id}/`,
    paperAdjust: (shop: number | string, id: number | string) => `/shops/${shop}/papers/${id}/adjust/`,
    finishingRates: (shop: number | string) => `/shops/${shop}/finishing-rates/`,
    finishingRate: (shop: number | string, id: number | string) => `/shops/${shop}/finishing-rates/${id}/`,
    machines: (shop: number | string) => `/shops/${shop}/machines/`,
    machine: (shop: number | string, id: number | string) => `/shops/${shop}/machines/${id}/`,
    printingRates: (machine: number | string) => `/machines/${machine}/printing-rates/`,
    printingRate: (machine: number | string, id: number | string) => `/machines/${machine}/printing-rates/${id}/`,
    rateCard: (shop: number | string) => `/shops/${shop}/rate-card/`,
  },
  quoteDrafts: {
    list: '/calculator/drafts/',
    detail: (id: number | string) => `/calculator/drafts/${id}/`,
    send: (id: number | string) => `/calculator/drafts/${id}/send/`,
    guest: '/calculator/guest-drafts/',
    claim: '/calculator/drafts/claim/',
    buyerQuotes: '/calculator/buyer-quotes/',
    directShopSubmit: (id: number | string) => `/calculator/drafts/${id}/direct-shop/submit/`,
  },
  calculator: {
    config: '/calculator/config/',
    publicPreview: '/calculator/public-preview/',
    preview: '/calculator/preview/',
    dashboardPreview: '/dashboard/calculator/preview/',
    artworkUpload: '/calculator/artwork-upload/',
    artworkDetail: (token: string) => `/calculator/artwork-upload/${token}/`,
    artworkPreview: (token: string) => `/calculator/artwork-upload/${token}/preview/`,
  },
  intake: {
    recommendedManagers: '/intake/recommended-managers/',
    submit: '/intake/submit/',
    publicRecommendedManagers: '/public/print-managers/recommended/',
  },
  offlineClaim: {
    claim: '/quotes/offline-claim/',
  },
  client: {
    home: '/dashboard/client-home/',
    counts: '/dashboard/counts/',
    quotes: '/dashboard/client/quotes/',
    quote: (id: number | string) => `/dashboard/client/quotes/${id}/`,
    jobs: '/dashboard/client/jobs/',
    job: (id: number | string) => `/dashboard/client/jobs/${id}/`,
    payments: '/dashboard/client/payments/',
    request: (id: number | string) => `/client/requests/${id}/`,
    responses: '/client/responses/',
    responseAccept: (id: number | string) => `/client/responses/${id}/accept/`,
    responseReject: (id: number | string) => `/client/responses/${id}/reject/`,
    responseReply: (id: number | string) => `/client/responses/${id}/reply/`,
  },
  quoteRequests: {
    list: '/workflow/quote-requests/',
    detail: (id: number | string) => `/workflow/quote-requests/${id}/`,
    responses: (id: number | string) => `/quote-requests/${id}/responses/`,
  },
  managedJobs: {
    list: '/managed-jobs/',
    files: (id: number | string) => `/managed-jobs/${id}/files/`,
    events: (id: number | string) => `/managed-jobs/${id}/events/`,
    settlement: (id: number | string) => `/managed-jobs/${id}/settlement/`,
    reorder: (id: number | string) => `/managed-jobs/${id}/reorder/`,
    markDelivered: (id: number | string) => `/managed-jobs/${id}/delivery/mark-delivered/`,
    confirmCompletion: (id: number | string) => `/managed-jobs/${id}/delivery/confirm/`,
    proofs: (id: number | string) => `/managed-jobs/${id}/files/proofs/`,
    artwork: (id: number | string) => `/managed-jobs/${id}/files/artwork/`,
    artworkConfirmationRequest: (id: number | string) => `/managed-jobs/${id}/artwork-confirmation/request/`,
    artworkConfirmationRespond: (id: number | string) => `/managed-jobs/${id}/artwork-confirmation/respond/`,
    payments: (id: number | string) => `/managed-jobs/${id}/payments/`,
    mpesaStkPush: (id: number | string) => `/managed-jobs/${id}/payments/mpesa/stk-push/`,
    mpesaQuery: (id: number | string) => `/managed-jobs/${id}/payments/mpesa/query/`,
  },
  jobFiles: {
    download: (id: number | string) => `/job-files/${id}/download/`,
    approve: (id: number | string) => `/job-files/${id}/approve/`,
    reject: (id: number | string) => `/job-files/${id}/reject/`,
    requestRevision: (id: number | string) => `/job-files/${id}/request-revision/`,
    markPrintReady: (id: number | string) => `/job-files/${id}/mark-print-ready/`,
  },
  assignments: {
    list: '/shop/assignments/',
    accept: (id: number | string) => `/job-assignments/${id}/accept/`,
    reject: (id: number | string) => `/job-assignments/${id}/reject/`,
    markInProduction: (id: number | string) => `/job-assignments/${id}/mark-in-production/`,
    markFinishing: (id: number | string) => `/job-assignments/${id}/mark-finishing/`,
    markReady: (id: number | string) => `/job-assignments/${id}/mark-ready/`,
    markCompleted: (id: number | string) => `/job-assignments/${id}/mark-completed/`,
    reportIssue: (id: number | string) => `/job-assignments/${id}/report-issue/`,
  },
  messages: {
    client: '/client/messages/',
    clientUnread: '/client/messages/unread-count/',
    clientRead: (id: number | string) => `/client/messages/${id}/read/`,
    shop: '/shop/messages/',
    shopUnread: '/shop/messages/unread-count/',
    shopRead: (id: number | string) => `/shop/messages/${id}/read/`,
  },
  admin: {
    home: '/dashboard/admin/',
  },
  partner: {
    home: '/dashboard/partner-home/',
    quotes: '/dashboard/partner/quotes/',
    quote: (id: number | string) => `/dashboard/partner/quotes/${id}/`,
    prefill: (id: number | string) => `/dashboard/manager/quote-requests/${id}/prefill/`,
    previewPricing: (id: number | string) => `/dashboard/manager/quote-requests/${id}/preview-pricing/`,
    shopOptions: (id: number | string) => `/dashboard/partner/quotes/${id}/shop-options/`,
    prepare: (id: number | string) => `/dashboard/partner/quotes/${id}/prepare/`,
    sendToClient: (id: number | string) => `/dashboard/partner/quotes/${id}/send-to-client/`,
    attachClient: (id: number | string) => `/dashboard/partner/quotes/${id}/attach-client/`,
    create: '/partner/quotes/create/',
    quotePreview: '/partner/quotes/preview/',
    productionMatches: '/partner/production-matches/',
    marketRates: '/dashboard/partner/market-rates/',
    profile: '/dashboard/partner/profile/',
    jobs: '/dashboard/partner/jobs/',
    job: (id: number | string) => `/dashboard/partner/jobs/${id}/`,
    dispatch: (id: number | string) => `/dashboard/partner/jobs/${id}/dispatch/`,
    clients: '/dashboard/partner/clients/',
    productionShops: '/dashboard/partner/production-shops/',
    payments: '/dashboard/partner/payments/',
  },
  production: {
    home: '/dashboard/production-home/',
    jobs: '/dashboard/production/jobs/',
    job: (id: number | string) => `/dashboard/production/jobs/${id}/`,
    breakdown: (id: number | string) => `/dashboard/printshop/jobs/${id}/breakdown/`,
    pricing: '/dashboard/production/pricing/',
    paperStock: '/dashboard/production/paper-stock/',
    finishings: '/dashboard/production/finishings/',
    payments: '/dashboard/production/payments/',
    shopHome: '/dashboard/shop-home/',
  },
  pricing: {
    preview: '/pricing/quote-financials/preview/',
    financials: (id: number | string) => `/pricing/quotes/${id}/financials/`,
  },
  payments: {
    mpesaStkPush: '/payments/mpesa/stk-push/',
    mpesaDetail: (id: number | string) => `/payments/mpesa/${id}/`,
    stkPush: '/payments/stk-push/',
    paymentDetail: (id: number | string) => `/payments/${id}/`,
    quoteAccept: (id: number | string) => `/quotes/${id}/accept/`,
  },
  contact: {
    submit: '/contact/submit/',
  },
} as const
